### ISSUE TITLE
A non-serializable value was detected in an action

### ISSUE THREAD

**Issue by Evgenus** [giantmachines/redux-websocket#101]
Redux requires actions to be serializable. Timestamp is a Date however API reference in readme says that it is string.

<img width="507" alt="зображення" src="https://user-images.githubusercontent.com/379412/73077783-87728780-3ec9-11ea-90e7-73ad99feb64e.png">

**Comment by procchio6** [comment]
Hi @Evgenus, thanks for submitting this issue. We will update the README to note that `meta.timestamp` is a data object. Since changing the timestamp to a string is a breaking change we will make this update for v2 of the library.

This error seems to be coming from [redux-toolkit middleware](https://github.com/reduxjs/redux-toolkit/blob/master/src/serializableStateInvariantMiddleware.ts) as was the case in issue https://github.com/giantmachines/redux-websocket/issues/80

**Comment by msutkowski** [comment]
I just wanted to leave a note here in case anyone stumbles on it. If you're using [redux-toolkit](https://redux-toolkit.js.org/) and bothered by the message, you can have the middleware ignore it by setting the `ignoredActionPaths` when calling `configureStore` like this:

```js
const store = configureStore({
  reducer: rootReducer,
  middleware: [
    ...getDefaultMiddleware({
      serializableCheck: {
        ignoredActionPaths: ['meta.arg', 'meta.timestamp'],
      },
    }),
   reduxWebsocketMiddleware,
   // ... your other middleware
  ],
});
```
