### ISSUE TITLE
Single Websocket Connection?

### ISSUE THREAD

**Issue by mfreeman-xtivia** [giantmachines/redux-websocket#34]
If I am reading the code correctly it would appear that this middleware only supports a single websocket connection at a time -- is that right?

i.e. there is no way to have multiple connections open and have the messages that are received passed back into redux with some indication of the connection to which they belong?

**Comment by brianmcallister** [comment]
Hey @mfreeman-xtivia, yep, you're correct that the currently published version only supports a single connection right now.

We're working on changing this library for our 1.0 release so that the library exports a middleware creator function, from which you can create multiple instances (and therefore multiple connections).

As soon as we get #37 merged, you should be able to open up multiple connections where the dispatched actions can have a prefixed action name (something like `CONNECTION_ONE::REDUX_WEBSOCKET::OPEN` and `CONNECTION_TWO::REDUX_WEBSOCKET::OPEN`, etc.).

**Comment by brianmcallister** [comment]
@mfreeman-xtivia I just published `1.0.0`. Check out the thread in #44 for an example of how you can support multiple connections. Let me know how it goes!
