### ISSUE TITLE
[Feature request] v1. Custom 'message' action creator

### ISSUE THREAD

**Issue by LittlePony** [giantmachines/redux-websocket#43]
New option for createWebsocket, something like 'onMessage' to replace builtin 'message' action creator.
This will allow the use of one websocket channel for different reducers.

**Comment by brianmcallister** [comment]
Hey @LittlePony, great suggestion. We are currently adding a feature to allow for custom prefixes in action names. That feature is targeted more towards the use case of handling multiple websocket connections.

However, you could structure your reducers so that actions can be handled by multiple. Could you provide a specific example in code of what you're trying to do?

**Comment by TPABHuKOB** [comment]
Nice, I also wanted to suggest it. 
@brianmcallister for example we have app with 10-20 messages per second throwed by websocket.
Redux performance guidelines https://redux.js.org/faq/performance suggest to avoid unnecessary dispatches.  So that is why we have function what filter websocket messages.
And yes, we can't change backend because that API used by other apps.

I think it must be option
```
store.dispatch({
  type: WEBSOCKET_CONNECT,
  payload: {
    url: 'wss://localhost:8080',
    onMessage: yourFunc
  }
})
```

**Comment by brianmcallister** [comment]
@TPABHuKOB I see what you mean. I think in the case where you have a large number of updates, you might want to consider not using Redux at all. 

For example, Giant Machines builds a lot of trading applications. Apps like this have multiple real time feeds, and usually at least one for price updates on whatever asset the application trades. Because we don't care about historical prices for assets (we would pull that from an API that served timeseries data), we've found that using a `BehaviorSubject` from the RxJS library has been more effective.

However, point taken, and providing a hook into message event in the way you're suggesting would be a valuable feature.

**Comment by TPABHuKOB** [comment]
@brianmcallister another case:
I want to have readable code. But with WEBSOCKET_MESSAGE my reducer will become messy like
```
switch (action.type) {
  case WEBSOCKET_MESSAGE: {
    switch(action.payload.event) {
      case 'SomethingAdd': {
        ...
      }
      case 'SomethingUpdate': {
        ...
      }
      case 'SomethingRemove': {
        ...
      }
      case 'SomthingHappen': {
        ...
      }
    }
    break;
  }
  case USER_ACTION_1: {
    ...
  }
  case USER_ACTION_2: {
    ...
  }
  case USER_ACTION_3: {
    ...
  }
}
```
Almost all my reducer will got WEBSOCKET_MESSAGE 'switch case' block. 
So i want to pass to middleware somthing like 'action creator'

**Comment by brianmcallister** [comment]
Going to close this because it's been open a long time, feel free to reopen if there's more discussion to be had.
