### ISSUE TITLE
Package not found in npm

### ISSUE THREAD

**Issue by W1ndst0rm** [giantmachines/redux-websocket#9]
I tried using npm to install the package using the command at https://github.com/giantmachines/redux-websocket#installation. It returns a 404 error.

```
>npm install @giantmachines/redux-websocket --save
npm ERR! code E404
npm ERR! 404 Not Found: @giantmachines/redux-websocket@latest
```

This looks like a great package and I'd love to see it more readily available.

**Comment by mathieux51** [comment]
Thanks to this [question](https://stackoverflow.com/questions/17509669/how-to-install-an-npm-package-from-github-directly) i tried 
```shell
npm install git+https://git@github.com/giantmachines/redux-websocket.git --save
```
and it worked

**Comment by odragora** [comment]
Yarn can't locate package as well.

**Comment by a-type** [comment]
If the author doesn't end up publishing in NPM, you can still install the dependency using `npm i --save https://github.com/giantmachines/redux-websocket.git`. Obviously not ideal.

**Comment by jheirtzler** [comment]
Has anyone contacted the authors about publishing this?

**Comment by hugows** [comment]
Installing with git://.. worked here, but the packager has errors finding/including the lib.

**Comment by a-type** [comment]
@hugows right, since they don't have the `dist` folder (transpiled sources) tracked in their Git repo, it won't work. You could workaround this by running `npm i && npm run build` in the library's directory inside your `node_modules`, but that will only work for the local machine and need to be repeated for all team members and every time you refresh `node_modules`.

FWIW, if the owners don't publish the package as public, someone could certainly fork their own and publish it to a personal namespace. I ended up just writing my own little socket module in my project that subscribes to events and makes them consumable by a `redux-saga` which converts incoming messages into actions. Sockets aren't super hard to work with.

Further reading on the subject:

* Websocket API (be sure to see the example near the bottom): https://developer.mozilla.org/en-US/docs/Web/API/WebSocket

* Using channels in redux-saga to listen to websocket events (scroll down for a code sample): https://redux-saga.js.org/docs/advanced/Channels.html

**Comment by tylerbuchea** [comment]
I created a PR (#10 ) that will fix this issue. Until then I have published the package under my own NPM account, so you can use my version for the time being:

```bash
yarn add @tylerbuchea/redux-websocket
```

**Comment by samuelcastro** [comment]
Tried to use your version @tylerbuchea but is not working for some reason as well, end up just creating mine: 
```
yarn add @samuelcastro/redux-websocket
```

Would be very helpful if the owner publish it so we can all have just entry point instead of creating many other versions.

**Comment by lyrixx** [comment]
Hello @brianmcallister 

Are you still supporting this lib?

Thanks

**Comment by brianmcallister** [comment]
Sorry everyone! This is a little bit of an older package, and I wasn't getting notifications until @lyrixx mentioned me.

So, I just did `yarn add @giantmachines/redux-websocket` and `npm i @giantmachines/redux-websocket -E`, and I was able to to install this package just fine.

Giant Machines does want to continue supporting this, so if anybody is still affected, please let me know.

**Comment by brianmcallister** [comment]
Just another quick update, I've published this as public on the npm registry, so hopefully this isn't a problem anymore.

I'm going to go ahead and close this issue for the time being, but if anyone has any further trouble, please open another issue or reach out directly.

**Comment by nick10811** [comment]
@brianmcallister I have the same issue.
